name = "vivo-gallery-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "458d9927b069594f4ef7c97674fa4cb2"

# 自定义域名路由
routes = ["vivo-image.kyeo.top/*"]

# 定时触发器：每30分钟执行一次爬虫
[triggers]
crons = ["*/30 * * * *"]

# 环境变量
[vars]
VIVO_USER_ID = "599660628355"

[[d1_databases]]
binding = "DB"
database_name = "vivo-gallery-db"
database_id = "d07449ee-5f8c-4be1-a21d-ad0c65632586"
